name: Mital Chat GPT Demo
on:
  push:
    branches:
      - main
jobs:
  first_task:
    runs-on: [self-hosted, linux, x64, ec2]
    steps:
      - uses: actions/checkout@master
        with:
          ref: main
      - uses: actions/setup-node@master
        with:
          node-version: 16.14.1
      - name: Install dependencies
        run:  npm install
      - name: Build 
        run: npm run build
      - name: "Upload to S3"
        uses: hkusu/s3-upload-action@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
          aws-bucket: ${{ secrets.AWS_S3_BUCKET }}
          file-path: "./build"
          destination-dir: "mital-demo-2"
