name: Mital Chat GPT Demo
on:
  push:
    branches:
      - main
jobs:
  first_task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: main
      - uses: actions/setup-node@master
        with:
          node-version: 14.15.5
      - name: Install dependencies
        run:  npm install
      - name: Build 
        run: npm run build
      - name: "Upload to S3"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
      - name: Deploy to S3 bucket
        run: aws s3 sync ./build/ s3://mital-demo-2 --delete
